# Makefile for the MegaFlashROM SCC+ SD driver for Nextor 3.
#
# By default builds four ROMs (combining this driver with the Nextor
# kernel base file pointed at by NEXTOR_BASE), placed in `bin/`:
#
#   * bin/Nextor-<ver>.MegaFlashSDSCC.1-slot.ROM             - 1-slot variant
#   * bin/Nextor-<ver>.MegaFlashSDSCC.1-slot.Recovery.ROM    - 1-slot, prefixed with the recovery header
#   * bin/Nextor-<ver>.MegaFlashSDSCC.2-slots.ROM            - 2-slots variant
#   * bin/Nextor-<ver>.MegaFlashSDSCC.2-slots.Recovery.ROM   - 2-slots, prefixed with the recovery header
#
# Intermediate build artifacts (.bin files produced by N80) go to
# `tmp/` and are dropped by `make clean`. The shippable ROMs in `bin/`
# survive `make clean` and are removed only by `make clean-bin` (or
# `make distclean` for both).
#
# <ver> is read from the SDK's nextor-kernel-version.txt (the authoritative
# kernel version, generated by the Nextor kernel Makefile from its version
# constants). Any variant suffix (e.g. ".NO_UNDOC.SHIFT_INV") is taken from the
# NEXTOR_BASE filename, which is expected to follow either the repository
# convention Nextor-<ver>.base[<suffix>].dat or the Docker image convention
# kernel_base[<suffix>].dat; a non-standard filename just yields no variant
# suffix.
#
# To build inside the Nextor dev Docker image instead of with a local
# toolchain, use the docker-build.sh wrapper (see README): the image provides
# N80, mknexrom, the SDK and the kernel base files, presetting NEXTOR_BASE and
# NEXTOR_SDK so this Makefile needs no extra configuration. To build against
# every kernel base variant in a directory (one `make` per base file), use
# build-all.sh, locally or via `docker-build.sh --variant all`.


### Configurable variables ###################################################

# NEXTOR_BASE: path to the Nextor kernel base .dat file (mandatory for
# every target except `setup` and the clean ones).
ifeq ($(strip $(NEXTOR_BASE)),)
ifeq ($(filter setup clean clean-bin distclean,$(MAKECMDGOALS)),)
$(error NEXTOR_BASE is not set. Point it at a Nextor kernel base .dat file)
endif
else
ifeq ($(wildcard $(NEXTOR_BASE)),)
$(error NEXTOR_BASE points at '$(NEXTOR_BASE)' which does not exist)
endif
endif

# NEXTOR_SDK: path to the Nextor SDK directory (the one containing 'asm/').
# Defaults to the bundled git submodule.
NEXTOR_SDK ?= external/Nextor/sdk

# Tool overrides. Default to invoking the executables from PATH.
N80      ?= N80
MKNEXROM ?= mknexrom

# NO_UNDOC_CPU_INSTRUCTIONS: when non-empty (e.g. =1) the driver is assembled
# with undocumented Z80 opcodes (those operating on ixh/ixl/iyh/iyl) replaced
# with documented equivalents, for compatibility with Z180-based MSX machines.
# It is inferred from the NEXTOR_BASE filename (see "Build flag inference"
# below): set when the base file's variant suffix contains NO_UNDOC, unset
# otherwise, so the driver always matches the kernel it is combined with. An
# explicit value (environment or command line, even an empty one) overrides
# the inference.


### Output directories #######################################################

BIN := bin
TMP := tmp


### Filename derivation ######################################################

# The kernel version for the ROM names comes from the SDK (authoritative):
# nextor-kernel-version.txt is generated by the Nextor kernel Makefile from
# its version constants, so the name always matches the kernel the SDK targets.
_VERSION_FILE         := $(NEXTOR_SDK)/nextor-kernel-version.txt
NEXTOR_KERNEL_VERSION := $(strip $(shell cat $(_VERSION_FILE) 2>/dev/null))

ifeq ($(NEXTOR_KERNEL_VERSION),)
ifeq ($(filter setup clean clean-bin distclean,$(MAKECMDGOALS)),)
$(error Could not read $(_VERSION_FILE). Is the Nextor SDK submodule initialized and up to date? Run 'make setup')
endif
endif

# The variant suffix (e.g. '.NO_UNDOC.SHIFT_INV') is a property of the base
# file, so it is taken from the NEXTOR_BASE filename. Two naming conventions
# are recognized, both carrying the suffix right after a 'base' token:
#   * the repository convention      'Nextor-<ver>.base[<suffix>].dat'
#   * the Docker image convention    'kernel_base[<suffix>].dat'
# A suffix is present only when 'base' is followed by a '.', so a plain
# '...base.dat' (or any non-standard filename) yields no variant suffix.
_BASE_NAME := $(notdir $(NEXTOR_BASE))
_BASE_STEM := $(_BASE_NAME:.dat=)
ifeq ($(findstring base.,$(_BASE_STEM)),base.)
_VARIANT := .$(lastword $(subst base., ,$(_BASE_STEM)))
else
_VARIANT :=
endif

### Build flag inference #####################################################

# The undoc-free kernel bases carry NO_UNDOC in their variant suffix, so unless
# the flag was given explicitly (`origin` is 'undefined' only when it was not
# set anywhere, and a deliberate empty value counts as set), derive it from
# the suffix. A base file with a non-standard name yields no suffix, hence no
# inference: set the flag by hand in that case.
ifeq ($(origin NO_UNDOC_CPU_INSTRUCTIONS),undefined)
NO_UNDOC_CPU_INSTRUCTIONS := $(if $(findstring NO_UNDOC,$(_VARIANT)),1,)
endif


### ROM names ################################################################

_DRIVER_PREFIX := Nextor-$(NEXTOR_KERNEL_VERSION).MegaFlashSDSCC

ROM_1SLOT           := $(BIN)/$(_DRIVER_PREFIX).1-slot$(_VARIANT).ROM
ROM_1SLOT_RECOVERY  := $(BIN)/$(_DRIVER_PREFIX).1-slot.Recovery$(_VARIANT).ROM
ROM_2SLOTS          := $(BIN)/$(_DRIVER_PREFIX).2-slots$(_VARIANT).ROM
ROM_2SLOTS_RECOVERY := $(BIN)/$(_DRIVER_PREFIX).2-slots.Recovery$(_VARIANT).ROM


### Assembly flags ###########################################################

N80_FLAGS := --no-string-escapes --no-show-banner --verbosity 0 \
             --build-type abs --output-file-extension bin \
             --output-file-case lower \
             --include-directory $(NEXTOR_SDK)

_DEFINES_NO_UNDOC := $(if $(NO_UNDOC_CPU_INSTRUCTIONS),--define-symbols NO_UNDOC_CPU_INSTRUCTIONS)


### Build-flag tracking ######################################################

# The NO_UNDOC setting changes how the driver is assembled but appears in no
# source file, so make can't see it change between runs. Record it in a stamp
# file that the intermediate .bin targets depend on: switching
# NO_UNDOC_CPU_INSTRUCTIONS then forces a reassembly instead of silently
# combining a mismatched (e.g. non-undoc) driver with a .NO_UNDOC kernel base.
# NUM_SLOTS doesn't need tracking: the 1-slot and 2-slots builds already go to
# distinct filenames, so there is no stale-reuse hazard for them.
_BUILD_ID    := undoc=$(if $(NO_UNDOC_CPU_INSTRUCTIONS),1,0)
_BUILD_STAMP := $(TMP)/.build-id

# Rewrite the stamp only when the id actually changes, so its mtime (and hence
# the rebuild) is triggered only on a real flag change. FORCE makes the recipe
# run every build to perform the check.
$(_BUILD_STAMP): FORCE | $(TMP)
	@printf '%s\n' '$(_BUILD_ID)' | cmp -s - $@ || printf '%s\n' '$(_BUILD_ID)' > $@


### Default target ###########################################################

# Set explicitly: the build-flag stamp rule above is the first target in the
# file, so without this `make` with no arguments would build only the stamp.
.DEFAULT_GOAL := all

.PHONY: all clean clean-bin distclean setup FORCE
all: $(ROM_1SLOT) $(ROM_1SLOT_RECOVERY) $(ROM_2SLOTS) $(ROM_2SLOTS_RECOVERY)

FORCE:

# Order-only prereqs for outputs that live in the build directories:
# ensure the directory exists without making its mtime affect rebuild
# decisions.
$(BIN) $(TMP):
	@mkdir -p $@


### Driver binaries (intermediates) ##########################################

# `driver.asm` (which also includes `romdisk.asm`) is assembled twice
# with different NUM_SLOTS to produce the 1-slot and 2-slots variants.

$(TMP)/driver.1slot.bin: driver.asm romdisk.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver.asm $(TMP)/driver.1slot.bin $(N80_FLAGS) $(_DEFINES_NO_UNDOC) --define-symbols NUM_SLOTS=1

$(TMP)/driver.2slots.bin: driver.asm romdisk.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) driver.asm $(TMP)/driver.2slots.bin $(N80_FLAGS) $(_DEFINES_NO_UNDOC) --define-symbols NUM_SLOTS=2

# The bank-switching routine for the ASCII8 mapper is the standard one
# shipped by the Nextor SDK.

$(TMP)/chgbnk.bin: $(NEXTOR_SDK)/asm/chgbnk/ascii8.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) $(NEXTOR_SDK)/asm/chgbnk/ascii8.asm $(TMP)/chgbnk.bin $(N80_FLAGS) $(_DEFINES_NO_UNDOC)

# 512-byte header prepended to the Recovery variants.

$(TMP)/recovery_header.bin: recovery_header.asm $(_BUILD_STAMP) | $(TMP)
	$(N80) recovery_header.asm $(TMP)/ $(N80_FLAGS) $(_DEFINES_NO_UNDOC)


### ROM combination via mknexrom (final outputs) #############################

$(ROM_1SLOT): $(TMP)/driver.1slot.bin $(TMP)/chgbnk.bin | $(BIN)
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/driver.1slot.bin /m:$(TMP)/chgbnk.bin

$(ROM_2SLOTS): $(TMP)/driver.2slots.bin $(TMP)/chgbnk.bin | $(BIN)
	$(MKNEXROM) $(NEXTOR_BASE) $@ /d:$(TMP)/driver.2slots.bin /m:$(TMP)/chgbnk.bin

# Recovery ROMs are the corresponding regular ROM with the recovery
# header concatenated in front.

$(ROM_1SLOT_RECOVERY): $(ROM_1SLOT) $(TMP)/recovery_header.bin | $(BIN)
	cat $(TMP)/recovery_header.bin $(ROM_1SLOT) > $@

$(ROM_2SLOTS_RECOVERY): $(ROM_2SLOTS) $(TMP)/recovery_header.bin | $(BIN)
	cat $(TMP)/recovery_header.bin $(ROM_2SLOTS) > $@


### Housekeeping #############################################################

# `make clean` keeps the shippable ROMs in bin/, only wipes intermediates.
clean:
	rm -rf $(TMP)

# `make clean-bin` removes the shippable ROMs.
clean-bin:
	rm -rf $(BIN)

# `make distclean` removes both.
distclean: clean clean-bin


### One-time setup ###########################################################

# `make setup` initializes the Nextor SDK submodule as a blobless
# partial clone with sparse-checkout for the `sdk/` directory only, so
# that the full Nextor repository is never fetched. Run this once,
# right after cloning this repo, instead of using `git clone
# --recurse-submodules`.
setup:
	@echo "Setting up the Nextor SDK submodule (blobless + sparse-checkout for sdk/ only)..."
	git submodule init external/Nextor
	git submodule update --init --filter=blob:none external/Nextor
	git -C external/Nextor sparse-checkout init --cone
	git -C external/Nextor sparse-checkout set sdk
	git -C external/Nextor checkout
	@echo "Done. Set NEXTOR_BASE and run 'make' to build."
